AllCops:
  TargetRubyVersion:
    2.6.2
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
    - 'spec/**/*'
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/admin/concerns/**/*'
    - 'lib/tasks/**/*'
    - 'config/**/*'
  DisplayCopNames: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentationStyle:
  IndentationWidth: 2

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Security/MarshalLoad:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
